server:
  port: ${PORT:8989}
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
    default-property-inclusion: non_null
    time-zone: UTC
app:
  newsapi:
    daysFrom: ${NEWS_API_DAYS:1}
    apiKey: ${NEWS_API_KEY:}
